create_clock -period 20.000 -name HCLK -waveform {0.000 10.000}

# REVISE BOTH ?
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {fcen_Sys0_S0[0]}]


set_property PACKAGE_PIN A18 [get_ports {fcen_Sys0_S0[0]}]
set_property PACKAGE_PIN V19 [get_ports {fd_Sys0_S0[3]}]
set_property PACKAGE_PIN W18 [get_ports {fd_Sys0_S0[2]}]
set_property PACKAGE_PIN W19 [get_ports {fd_Sys0_S0[1]}]
set_property PACKAGE_PIN T17 [get_ports {fd_Sys0_S0[0]}]
set_property PACKAGE_PIN D19 [get_ports {fsclk_Sys0_S0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fd_Sys0_S0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fd_Sys0_S0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fd_Sys0_S0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fd_Sys0_S0[0]}]
set_property PACKAGE_PIN T18 [get_ports {GPIO_Sys0_S2[15]}]
set_property PACKAGE_PIN U17 [get_ports {GPIO_Sys0_S2[14]}]
set_property PACKAGE_PIN U18 [get_ports {GPIO_Sys0_S2[13]}]
set_property PACKAGE_PIN V16 [get_ports {GPIO_Sys0_S2[12]}]
set_property PACKAGE_PIN V17 [get_ports {GPIO_Sys0_S2[11]}]
set_property PACKAGE_PIN W16 [get_ports {GPIO_Sys0_S2[10]}]
set_property PACKAGE_PIN W17 [get_ports {GPIO_Sys0_S2[9]}]
set_property PACKAGE_PIN V15 [get_ports {GPIO_Sys0_S2[8]}]
set_property PACKAGE_PIN W15 [get_ports {GPIO_Sys0_S2[7]}]
set_property PACKAGE_PIN W13 [get_ports {GPIO_Sys0_S2[6]}]
set_property PACKAGE_PIN W14 [get_ports {GPIO_Sys0_S2[5]}]
set_property PACKAGE_PIN U15 [get_ports {GPIO_Sys0_S2[4]}]
set_property PACKAGE_PIN U16 [get_ports {GPIO_Sys0_S2[3]}]
set_property PACKAGE_PIN V13 [get_ports {GPIO_Sys0_S2[2]}]
set_property PACKAGE_PIN V14 [get_ports {GPIO_Sys0_S2[1]}]
set_property PACKAGE_PIN U14 [get_ports {GPIO_Sys0_S2[0]}]
set_property PACKAGE_PIN K18 [get_ports {MSI_Sys0_SS0_S2[0]}]
set_property PACKAGE_PIN L18 [get_ports {MSI_Sys0_SS0_S3[0]}]
set_property PACKAGE_PIN G17 [get_ports {MSO_Sys0_SS0_S2[0]}]
set_property PACKAGE_PIN H17 [get_ports {MSO_Sys0_SS0_S3[0]}]
set_property PACKAGE_PIN D18 [get_ports {pwm_Sys0_SS0_S6[0]}]
set_property PACKAGE_PIN D17 [get_ports {pwm_Sys0_SS0_S7[0]}]
set_property PACKAGE_PIN J18 [get_ports {RsRx_Sys0_SS0_S0[0]}]
set_property PACKAGE_PIN J17 [get_ports {RsRx_Sys0_SS0_S1[0]}]
set_property PACKAGE_PIN G19 [get_ports {RsTx_Sys0_SS0_S0[0]}]
set_property PACKAGE_PIN H19 [get_ports {RsTx_Sys0_SS0_S1[0]}]
set_property PACKAGE_PIN U19 [get_ports {scl_Sys0_SS0_S4[0]}]
set_property PACKAGE_PIN R18 [get_ports {scl_Sys0_SS0_S5[0]}]
set_property PACKAGE_PIN E19 [get_ports {SCLK_Sys0_SS0_S2[0]}]
set_property PACKAGE_PIN E18 [get_ports {SCLK_Sys0_SS0_S3[0]}]
set_property PACKAGE_PIN P18 [get_ports {sda_Sys0_SS0_S4[0]}]
set_property PACKAGE_PIN F18 [get_ports {SSn_Sys0_SS0_S2[0]}]
set_property PACKAGE_PIN P17 [get_ports {sda_Sys0_SS0_S5[0]}]
set_property PACKAGE_PIN G18 [get_ports {SSn_Sys0_SS0_S3[0]}]
set_property PACKAGE_PIN N18 [get_ports {SYSTICKCLKDIV[7]}]
set_property PACKAGE_PIN N19 [get_ports {SYSTICKCLKDIV[6]}]
set_property PACKAGE_PIN P19 [get_ports {SYSTICKCLKDIV[5]}]
set_property PACKAGE_PIN R19 [get_ports {SYSTICKCLKDIV[4]}]
set_property PACKAGE_PIN M19 [get_ports {SYSTICKCLKDIV[3]}]
set_property PACKAGE_PIN L17 [get_ports {SYSTICKCLKDIV[2]}]
set_property PACKAGE_PIN K17 [get_ports {SYSTICKCLKDIV[1]}]
set_property PACKAGE_PIN N17 [get_ports {SYSTICKCLKDIV[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fsclk_Sys0_S0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_Sys0_S2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MSI_Sys0_SS0_S2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MSI_Sys0_SS0_S3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MSO_Sys0_SS0_S2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {MSO_Sys0_SS0_S3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_Sys0_SS0_S6[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwm_Sys0_SS0_S7[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RsRx_Sys0_SS0_S0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RsRx_Sys0_SS0_S1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sda_Sys0_SS0_S4[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RsTx_Sys0_SS0_S0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RsTx_Sys0_SS0_S1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scl_Sys0_SS0_S4[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scl_Sys0_SS0_S5[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SCLK_Sys0_SS0_S2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SCLK_Sys0_SS0_S3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sda_Sys0_SS0_S5[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSn_Sys0_SS0_S2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSn_Sys0_SS0_S3[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SYSTICKCLKDIV[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SYSTICKCLKDIV[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SYSTICKCLKDIV[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SYSTICKCLKDIV[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SYSTICKCLKDIV[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SYSTICKCLKDIV[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SYSTICKCLKDIV[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SYSTICKCLKDIV[0]}]


set_property PACKAGE_PIN U4 [get_ports HCLK]
set_property PACKAGE_PIN V7 [get_ports HRESETn]
set_property IOSTANDARD LVCMOS33 [get_ports HCLK]
set_property IOSTANDARD LVCMOS33 [get_ports HRESETn]
set_property PACKAGE_PIN U7 [get_ports NMI]
set_property IOSTANDARD LVCMOS33 [get_ports NMI]

